export const mainStage = [
  {
    id: 1,
    speaker: "Sony",
    category: "Přednáška",
    name: "Novinky a Síla Sony Systému",
    time: "9:15 - 10:00",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 2,
    speaker: "František Konopa",
    category: "Přednáška",
    name: "Jak pracovat s náladou a myšlenkou ve fotce",
    time: "10:15 - 11:15",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 3,
    speaker: "Honza Hvízdal",
    category: "Přednáška",
    name: "Zmrzlé světy",
    time: "11:30 - 12:30",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 4,
    speaker: "Histogram",
    category: "Přednáška",
    name: "Kdy vezme AI práci fotografům?",
    time: "12:45 - 13:30",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 5,
    speaker: "PeakDesign & Honza Březina",
    category: "Přednáška",
    name: "Japonsko",
    time: "13:45 - 15:00",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 6,
    speaker: "Jakub Mařík",
    category: "Přednáška",
    name: "Jak prodat svojí práci (nejen) online",
    time: "15:15 - 16:30",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  // {
  //   id: 7,
  //   speaker: "Marian Chytka",
  //   category: "Přednáška",
  //   name: "sportovní fotka (nevyplňovat do programu)",
  //   time: "16:45 - 17:45",
  //   hasRegistration: false,
  //   isPaid: false,
  //   isFull: false,
  //   shopLink: "#",
  // },
];

export const cafe = [
  {
    id: 1,
    speaker: "Jozef Sádecký",
    category: "Přednáška",
    name: "Krajinka",
    time: "9:00 - 9:45",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 2,
    speaker: "Manfrotto",
    category: "Přednáška",
    name: "Jak si vybrat stativ",
    time: "10:00 - 10:45",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 3,
    speaker: "Tomáš Fongus",
    category: "Přednáška",
    name: "Co obnáší fotit/točit (pro) prezidenta",
    time: "11:00 - 11:45",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 4,
    speaker: "Canon",
    category: "Přednáška",
    name: "Novinky u Canonu",
    time: "12:00 - 13:00",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 5,
    speaker: "Ondra Mašek",
    category: "Přednáška",
    name: "S kamerou kolem světa",
    time: "13:15 - 14:15",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 6,
    speaker: "Terka Tecí Němečková",
    category: "Přednáška",
    name: "Komunikace s klientem",
    time: "14:30 - 15:15",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 7,
    speaker: "Radek Karko",
    category: "Přednáška",
    name: "Wildlife",
    time: "15:30 - 16:30",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 8,
    speaker: "Leoš Kastner",
    category: "Přednáška",
    name: "Filmová režie a natáčení filmu Zbojník",
    time: "15:30 - 16:30",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
];

// Nádvoří
export const outdoor1 = [
  {
    id: 1,
    speaker: "Histogram",
    category: "Workshop",
    name: "Instantní fotografie jako přidaná hodnota vašich služeb aneb základy s polaroidem",
    time: "9:15 - 10:15",
    hasRegistration: true,
    isPaid: true,
    isFull: false,
    shopLink:
      "https://www.phototools.cz/zbozi/portret-s-canonem-workshop-na-foto-fest-plzen/",
  },
  {
    id: 2,
    speaker: "Sony",
    category: "Workshop",
    name: "Portrét v přirozeném světle s Janem Tichým",
    time: "10:30 - 12:00",
    hasRegistration: true,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 3,
    speaker: "Peak Design",
    category: "Workshop",
    name: "Lifestyle portrét s You’n'me",
    time: "12:15 - 13:45",
    hasRegistration: true,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 4,
    speaker: "Nikon",
    category: "Workshop",
    name: "Filip barták čb portrét",
    time: "14:00 - 15:15",
    hasRegistration: true,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 5,
    speaker: "Terka Tecí Němečková",
    category: "Workshop",
    name: "Předsvatební focení ",
    time: "15:30 - 16:15",
    hasRegistration: true,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 6,
    speaker: "Canon",
    category: "Workshop",
    name: "Focení portrétu s EOS R systémem",
    time: "16:30 - 17:45",
    hasRegistration: true,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
];

// Nádvoří
export const outdoor2 = [
  {
    id: 1,
    speaker: "Petr Klempa",
    category: "Workshop",
    name: "Portrét",
    time: "10:15 - 11:15",
    hasRegistration: true,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 2,
    speaker: "Dominik Beránek",
    category: "Workshop",
    name: "Street portrét",
    time: "11:30 - 12:30",
    hasRegistration: true,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 3,
    speaker: "František Konopa",
    category: "Workshop",
    name: "Emoce v portrétu",
    time: "12:45 - 13:45",
    hasRegistration: true,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 4,
    speaker: "Histogram",
    category: "Workshop",
    name: "Instantní fotografie jako přidaná hodnota vašich služeb aneb základy s polaroidem",
    time: "14:00 - 15:00",
    hasRegistration: true,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 5,
    speaker: "Lukáš Kenji Vrábel",
    category: "Workshop",
    name: "Lifestyle portrét",
    time: "15:15 - 16:45",
    hasRegistration: true,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  // {
  //   id: 6,
  //   speaker: "",
  //   category: "Workshop",
  //   name: "",
  //   time: "",
  //   hasRegistration: true,
  //   isPaid: false,
  //   isFull: false,
  //   shopLink: "#",
  // },
];

// Klempírna
export const klempirna = [
  {
    id: 1,
    speaker: "Manfrotto",
    category: "Přednáška",
    name: "Jak vybrat stativ a příslušenství",
    time: "10:15 - 11:15",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 2,
    speaker: "Sony",
    category: "Přednáška",
    name: "Síla Sony systému",
    time: "11:30 - 12:30",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 3,
    speaker: "Miloš Nejezchleb",
    category: "Přednáška",
    name: "Art fotografie",
    time: "12:45 - 13:45",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 4,
    speaker: "F22 - Michal Houdek",
    category: "Workshop",
    name: "Fotíme motorku prakticky",
    time: "14:30 - 15:30",
    hasRegistration: true,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 5,
    speaker: "Jiří Lízler",
    category: "Přednáška",
    name: "Marketing pro fotografy",
    time: "15:45 - 16:45",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 6,
    speaker: "FullFace - Martin Vrbický a Štěpán Romanov",
    category: "Přednáška",
    name: "Natáčení v outdooru",
    time: "17:00 - 18:00",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
];

// Ateliér
export const atelier = [
  {
    id: 1,
    speaker: "ViewSonic",
    category: "Přednáška",
    name: "Jak na barvy na monitoru",
    time: "10:30 - 11:30",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 2,
    speaker: "Tamron - Lukáš Szwejdar",
    category: "Workshop",
    name: "Glamour fotografie",
    time: "11:45 - 12:45",
    hasRegistration: true,
    isPaid: false,
    isFull: true,
    shopLink: "#",
  },
  {
    id: 3,
    speaker: "Canon",
    category: "Přednáška",
    name: "EOS R – síla bajonetu, technologická současnost i budoucnost systému Canon EOS",
    time: "13:00 - 14:00",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 4,
    speaker: "Petr Dudek",
    category: "Přednáška",
    name: "Portréty a svatby",
    time: "14:15 - 15:15",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 5,
    speaker: "Mayhempictures - Zbyněk Mach",
    category: "Přednáška",
    name: "Focení automotive",
    time: "15:30 - 16:30",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 6,
    speaker: "Milan Říský",
    category: "Přednáška",
    name: "Koncertní fotografie",
    time: "16:45 - 17:45",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 7,
    speaker: "Martin Koudela",
    category: "Přednáška",
    name: "Timelapse",
    time: "18:00 - 19:00",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
];

// Kontejnery
export const kontejnery = [
  {
    id: 1,
    speaker: "Tereza Václavová",
    category: "Přednáška",
    name: "Svatební focení - tipy a rady ",
    time: "10:00 - 11:00",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 2,
    speaker: "Radek Karko",
    category: "Přednáška",
    name: "Wildlife video, sport, Afrika",
    time: "11:30 - 12:30",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 3,
    speaker: "F22 - Michal Houdek",
    category: "Přednáška",
    name: "Jak fotit motorku",
    time: "12:45 - 13:45",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 4,
    speaker: "Kvalitní fotky - Petr Komárek",
    category: "Přednáška",
    name: "Systém pro fotografy",
    time: "14:00 - 15:00",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 5,
    speaker: "Leica Klub",
    category: "Přednáška",
    name: "Leica a vše kolem",
    time: "15:15 - 16:15",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 6,
    speaker: "Vojta Pollák",
    category: "Přednáška",
    name: "FPV drony",
    time: "17:00 - 18:00",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
];

// Nádvoří
export const nadvori = [
  {
    id: 1,
    speaker: "Canon",
    category: "Workshop",
    name: "Portrét s Canonem",
    time: "10:00 - 11:30",
    hasRegistration: true,
    isPaid: true,
    isFull: false,
    shopLink:
      "https://www.phototools.cz/zbozi/portret-s-canonem-workshop-na-foto-fest-plzen/",
  },
  {
    id: 2,
    speaker: "Nikon - Filip Barták",
    category: "Workshop",
    name: "Photowalk s Nikonem",
    time: "11:45 - 12:45",
    hasRegistration: true,
    isPaid: false,
    isFull: true,
    shopLink: "#",
  },
  {
    id: 3,
    speaker: "Peak Design - You'N'Me",
    category: "Workshop",
    name: "Fotky s příběhem",
    time: "11:45 - 12:45",
    hasRegistration: true,
    isPaid: false,
    isFull: true,
    shopLink: "#",
  },
  {
    id: 4,
    speaker: "Sony - Jan Tichý",
    category: "Workshop",
    name: "Zachyťte přirozený portrét se Sony",
    time: "14:00 - 15:00",
    hasRegistration: true,
    isPaid: true,
    isFull: false,
    shopLink:
      "https://www.phototools.cz/zbozi/zachytte-prirozeny-portret-se-sony-workshop-na-foto-fest-plzen-2022/",
  },
  {
    id: 5,
    speaker: "Manfrotto - Lukáš Navara",
    category: "Workshop",
    name: "Portréty",
    time: "15:30 - 16:30",
    hasRegistration: true,
    isPaid: false,
    isFull: true,
    shopLink: "#",
  },
  {
    id: 6,
    speaker: "Dominik Beránek",
    category: "Workshop",
    name: "Street portrét",
    time: "16:45 - 17:45",
    hasRegistration: true,
    isPaid: false,
    isFull: true,
    shopLink: "#",
  },
  {
    id: 7,
    speaker: "Tomáš Košňar + Leica klub",
    category: "Workshop",
    name: "Focení na analog a film (technika k zapůjčení na místě)",
    time: "18:00 - 19:00",
    hasRegistration: true,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
];
