export const mainStage = [
  {
    id: 1,
    speaker: "Jiří Lízler",
    category: "Přednáška",
    name: "Marketing pro fotografy",
    time: "10:00 - 11:00",
    hasRegistration: false,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 2,
    speaker: "Michaela Rusaňuková",
    category: "Přednáška",
    name: "Psychologie ve fotce",
    time: "11:15 - 12:45",
    hasRegistration: false,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 3,
    speaker: "Mockup space",
    category: "Přednáška",
    name: "Nekonečná inspirace: Jak nevyhořet v kreativě, motivace a balance",
    time: "13:00 - 14:00",
    hasRegistration: false,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 4,
    speaker: "PeakDesign | Jan Březina",
    category: "Přednáška",
    name: "Jak cestovat s fototechniku bezpečně po celém světě",
    time: "14:15 - 15:30",
    hasRegistration: false,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 5,
    speaker: "Canon",
    category: "Přednáška",
    name: "EOS R systémem",
    time: "15:45 - 16:30",
    hasRegistration: false,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 6,
    speaker: "Nikon | Matěj Šmucr",
    category: "Přednáška",
    name: "Expedice do Afriky",
    time: "16:45 - 17:45",
    hasRegistration: false,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
];

export const cafe = [
  {
    id: 1,
    speaker: "Milan  Říský",
    category: "Přednáška",
    name: "Tajemství koncertní fotografie",
    time: "10:15 - 11:15",
    hasRegistration: false,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 2,
    speaker: "Eizo",
    category: "Přednáška",
    name: "Slaďte si obrázek na monitoru s tiskem",
    time: "11:30 - 12:30",
    hasRegistration: false,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 3,
    speaker: "Sony",
    category: "Přednáška",
    name: "Novinky od Sony",
    time: "12:45 - 13:30",
    hasRegistration: false,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 4,
    speaker: "Domes",
    category: "Přednáška",
    name: "Tvorba contentu a správa IG",
    time: "14:00 - 14:30",
    hasRegistration: false,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 5,
    speaker: "Petr Suchý",
    category: "Přednáška",
    name: "Jak se točí diplomacie",
    time: "14:45 - 15:30",
    hasRegistration: false,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 6,
    speaker: "",
    category: "Přednáška",
    name: "Náhlédnutí do zakulisí audiovizuálního studia BIKES ON FILM + Q&A",
    time: "16:00 - 17:00",
    hasRegistration: false,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 7,
    speaker: "Vítek Kanyza",
    category: "Promítání",
    name: "Jeden den na Haiti",
    time: "17:15 - 18:15",
    hasRegistration: false,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
];

// Nádvoří
export const outdoor1 = [
  {
    id: 1,
    speaker: "Fujifilm | Maria Bartošová",
    category: "Workshop",
    name: "Základy focení jídla",
    time: "11:00 - 12:00",
    hasRegistration: true,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 2,
    speaker: "František Konopa",
    category: "Workshop",
    name: "Vizuální storytelling",
    time: "12:30 - 13:30",
    hasRegistration: true,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 3,
    speaker: "Michaela Rusaňuková",
    category: "Workshop",
    name: "Psychologie ve fotce",
    time: "14:00 - 15:00",
    hasRegistration: true,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 4,
    speaker: "Mockup space",
    category: "Workshop",
    name: "Kreativní lifestyle produktová fotografie",
    time: "15:30 - 17:30",
    hasRegistration: true,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
];

// Nádvoří
export const outdoor2 = [
  {
    id: 1,
    speaker: "Nikon",
    category: "Workshop",
    name: "Kreativní výrazový portrét",
    time: "10:30 - 11:30",
    hasRegistration: true,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 2,
    speaker: "Dominik Beránek",
    category: "Workshop",
    name: "Photosession",
    time: "11:45 - 12:45",
    hasRegistration: true,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 3,
    speaker: "Peakdesign | Jan Březina a Irma Březinová",
    category: "Workshop",
    name: "Světlo a postava",
    time: "12:30 - 13:30",
    hasRegistration: true,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 4,
    speaker: 'Lukáš "Kenji" Vrábel',
    category: "Workshop",
    name: "Párové focení: Tipy a triky pro nezapomenutelné momenty",
    time: "13:45 - 15:00",
    hasRegistration: true,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 5,
    speaker: "Sony | Jan Tichý",
    category: "Workshop",
    name: "Portrét s umělým světlem s Janem Tichým",
    time: "15:15 - 16:15",
    hasRegistration: true,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 6,
    speaker: "Canon",
    category: "Workshop",
    name: "Focení portrétů s EOS R systémem",
    time: "16:30 - 17:30",
    hasRegistration: true,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
];
