export const mainStage = [
  {
    id: 1,
    speaker: "Sony",
    category: "Přednáška",
    name: "Alfa systém",
    time: "10:00 - 10:45",
    hasRegistration: false,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 2,
    speaker: "Michaela Rusaňuková",
    category: "Přednáška",
    name: "Psychologie ve fotce",
    time: "11:00 - 12:30",
    hasRegistration: false,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 3,
    speaker: "Mockup space",
    category: "Přednáška",
    name: "Mockup space",
    time: "12:45 - 13:45",
    hasRegistration: false,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 4,
    speaker: "Canon",
    category: "Přednáška",
    name: "EOS R systémem",
    time: "14:00 - 14:45",
    hasRegistration: false,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
];

export const cafe = [
  {
    id: 1,
    speaker: "Milan  Říský",
    category: "Přednáška",
    name: "Koncert",
    time: "10:30 - 11:30",
    hasRegistration: false,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 2,
    speaker: "Jan Březina - Peakdesign",
    category: "Přednáška",
    name: "Cestovateslká fotka",
    time: "11:45 - 12:45",
    hasRegistration: false,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 3,
    speaker: "Matěj Šmucr",
    category: "Přednáška",
    name: "Expedice do afriky",
    time: "13:15 - 14:15",
    hasRegistration: false,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 4,
    speaker: "Domes",
    category: "Přednáška",
    name: "Tvorba contentu a správa IG",
    time: "14:30 - 15:00",
    hasRegistration: false,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 5,
    speaker: "Petr Suchý",
    category: "Přednáška",
    name: "Jak se točí diplomacie",
    time: "15:15 - 16:00",
    hasRegistration: false,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 6,
    speaker: "Bikes on film",
    category: "Přednáška",
    name: "Sportovní fotka/video",
    time: "16:15 - 17:15",
    hasRegistration: false,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 7,
    speaker: "Vítek Kanyza",
    category: "Přednáška",
    name: "Film o Haiti",
    time: "17:30 - 18:30",
    hasRegistration: false,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
];

// Nádvoří
export const outdoor1 = [
  {
    id: 1,
    speaker: "Maria Bartošová",
    category: "Workshop",
    name: "Fujifilm - Základy focení jídla",
    time: "11:15 - 12:15",
    hasRegistration: true,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 2,
    speaker: "František Konopa",
    category: "Workshop",
    name: "František Konopa",
    time: "12:30 - 13:30",
    hasRegistration: true,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 3,
    speaker: "Michaela Rusaňuková",
    category: "Workshop",
    name: "Psychologie ve fotce",
    time: "14:00 - 15:00",
    hasRegistration: true,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 4,
    speaker: "Canon",
    category: "Workshop",
    name: "Focení portrétů s EOS R systémem",
    time: "15:15 - 16:15",
    hasRegistration: true,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 5,
    speaker: "Kenji",
    category: "Workshop",
    name: "Street",
    time: "16:30 - 17:30",
    hasRegistration: true,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
];

// Nádvoří
export const outdoor2 = [
  {
    id: 1,
    speaker: "Eizo",
    category: "Workshop",
    name: "Slaďte si obrázek na monitoru s tiskem",
    time: "10:00 - 11:00",
    hasRegistration: true,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 2,
    speaker: "Nikon",
    category: "Workshop",
    name: "Portrét",
    time: "11:15 - 12:15",
    hasRegistration: true,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 3,
    speaker: "Sony - Jan Tichý",
    category: "Workshop",
    name: "Portrét v přirozeném světle s Janem Tichým",
    time: "12:30 - 13:30",
    hasRegistration: true,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 4,
    speaker: "Mockup space",
    category: "Workshop",
    name: "Mockup space",
    time: "14:00 - 15:00",
    hasRegistration: true,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  {
    id: 5,
    speaker: "Jan Březina + Paní Březinová - Peakdesign",
    category: "Workshop",
    name: "Svatební fotka",
    time: "15:15 - 16:15",
    hasRegistration: true,
    isPaid: false,
    price: "0 Kč",
    isFull: false,
    shopLink: "#",
    optionalMessage: "",
  },
  // {
  //   id: 6,
  //   speaker: "",
  //   category: "Workshop",
  //   name: "",
  //   time: "",
  //   hasRegistration: true,
  //   isPaid: false,
  //   isFull: false,
  //   shopLink: "#",
  //   optionalMessage: "",
  // },
];
